/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MiroirNodeStatusApplyConfiguration represents a declarative configuration of the MiroirNodeStatus type for use
// with apply.
//
// MiroirNodeStatus is the pool capacity this node's agent publishes for
// capacity-aware placement and overcommit guardrails.
type MiroirNodeStatusApplyConfiguration struct {
	// Pools carries one capacity entry per storage pool on this node.
	Pools []MiroirNodePoolStatusApplyConfiguration `json:"pools,omitempty"`
	// DRBDVersion is the DRBD kernel module version the agent probed at
	// startup (e.g. "9.3.2"); absent on nodes without the module. The
	// module ships with the host, not the agent image, so this is the
	// per-node view that makes mixed clusters visible mid-upgrade.
	DRBDVersion *string `json:"drbdVersion,omitempty"`
	// DRBDUtilsVersion is the drbd-utils userland version the agent
	// probed at startup (e.g. "9.34.3"). Unlike the kernel module the
	// utils ship in the agent image, so this varies per agent rollout
	// rather than per host.
	DRBDUtilsVersion *string `json:"drbdUtilsVersion,omitempty"`
	// ObservedAt is when these figures were last sampled; the controller
	// ignores stats older than a few poll intervals as unknown.
	ObservedAt *v1.Time `json:"observedAt,omitempty"`
	// Conditions follow the standard Kubernetes condition conventions;
	// PoolUsageHigh fires at the 80% data/metadata warn line (any pool)
	// and StorageWedged while the node-scoped command breaker is open.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MiroirNodeStatusApplyConfiguration constructs a declarative configuration of the MiroirNodeStatus type for use with
// apply.
func MiroirNodeStatus() *MiroirNodeStatusApplyConfiguration {
	return &MiroirNodeStatusApplyConfiguration{}
}

// WithPools adds the given value to the Pools field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Pools field.
func (b *MiroirNodeStatusApplyConfiguration) WithPools(values ...*MiroirNodePoolStatusApplyConfiguration) *MiroirNodeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPools")
		}
		b.Pools = append(b.Pools, *values[i])
	}
	return b
}

// WithDRBDVersion sets the DRBDVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DRBDVersion field is set to the value of the last call.
func (b *MiroirNodeStatusApplyConfiguration) WithDRBDVersion(value string) *MiroirNodeStatusApplyConfiguration {
	b.DRBDVersion = &value
	return b
}

// WithDRBDUtilsVersion sets the DRBDUtilsVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DRBDUtilsVersion field is set to the value of the last call.
func (b *MiroirNodeStatusApplyConfiguration) WithDRBDUtilsVersion(value string) *MiroirNodeStatusApplyConfiguration {
	b.DRBDUtilsVersion = &value
	return b
}

// WithObservedAt sets the ObservedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedAt field is set to the value of the last call.
func (b *MiroirNodeStatusApplyConfiguration) WithObservedAt(value v1.Time) *MiroirNodeStatusApplyConfiguration {
	b.ObservedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MiroirNodeStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *MiroirNodeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
