package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DefaultPoolName is the storage pool a replica, StorageClass, or node
// entry means when it names none — the identity every pre-multi-pool
// object is adopted under. Owned here so every layer (nodemap, agents,
// controller) normalizes against the same constant.
const DefaultPoolName = "default"

// BackendType selects the node-local storage backend for a replica.
// +kubebuilder:validation:Enum=lvmthin;zfs;loopfile
type BackendType string

const (
	BackendLVMThin BackendType = "lvmthin"
	BackendZFS     BackendType = "zfs"
	// BackendLoopfile stores volumes as loop-backed sparse files on the
	// node's existing filesystem (no dedicated disk or pool).
	BackendLoopfile BackendType = "loopfile"
)

// QuorumPolicy selects the 2-node consistency mode.
// +kubebuilder:validation:Enum=last-man-standing;freeze
type QuorumPolicy string

const (
	QuorumLastManStanding QuorumPolicy = "last-man-standing"
	QuorumFreeze          QuorumPolicy = "freeze"
)

// VolumePhase is the coarse lifecycle state of a volume.
type VolumePhase string

const (
	VolumeCreating VolumePhase = "Creating"
	VolumeReady    VolumePhase = "Ready"
	VolumeDegraded VolumePhase = "Degraded"
	VolumeFailed   VolumePhase = "Failed"
)

// ConditionNodeUnreachable indicates that volume provisioning was
// blocked because a node's agent has not reported status within the
// staleness threshold. Set by the CSI controller when waitReady times
// out; cleared when provisioning succeeds. Informational — does not
// gate staging.
const ConditionNodeUnreachable = "NodeUnreachable"

// ConditionOrphaned indicates that no PersistentVolume shares this
// volume's name, so nothing in the cluster references the storage it
// still holds — thin-pool space, a DRBD minor, a replication port, and a
// full set of miroir_volume_* series. Raised by the orphan sweep once the
// provisioning grace period has passed; cleared if a PV appears. Whether
// it is then collected is opt-in (--orphan-volume-reap-after); on its own
// the condition only makes the leak visible.
const ConditionOrphaned = "Orphaned"

// Replica is one placement of the volume's data — a DRBD peer when the
// volume is replicated.
type Replica struct {
	// Node is the Kubernetes node name hosting this replica.
	Node string `json:"node"`
	// Backend selects how the backing device is provisioned on this node.
	// Unused for diskless tie-breaker replicas (they have no backing device).
	// +optional
	Backend BackendType `json:"backend,omitempty"`
	// Pool names the node-map storage pool holding this replica's backing
	// device. Persisted like Backend so the volume survives later topology
	// edits. Empty means the default pool (pre-multi-pool volumes are
	// adopted this way). Unused for diskless replicas.
	// +optional
	Pool string `json:"pool,omitempty"`
	// NodeID is the DRBD node id, assigned by the controller at creation
	// and stable for the volume's lifetime. Only set on replicated volumes.
	// +optional
	NodeID int32 `json:"nodeID,omitempty"`
	// Address is the replication endpoint (host IP), from the node map.
	// Only set on replicated volumes.
	// +optional
	Address string `json:"address,omitempty"`
	// FullSync marks a replica added after volume creation: its agent
	// skips the day0 GI seed so DRBD full-syncs it from the existing
	// peers instead of treating it as a pristine twin. Set by the
	// membership reconciler when it completes the entry.
	// +optional
	FullSync bool `json:"fullSync,omitempty"`
	// Diskless makes this a quorum-only tie-breaker: DRBD joins for
	// voting but stores no data. No backend device, never a mount
	// target. The agent skips backend create/resize/delete and DRBD
	// create-md; the resource renders "disk none" for this peer.
	// +optional
	Diskless bool `json:"diskless,omitempty"`
}

// DRBDSpec carries the cluster-unique DRBD identifiers allocated by the
// controller. The Minor is per-node and managed locally by each agent.
// Unset for replicas:1 volumes (no replication layer).
type DRBDSpec struct {
	// Port is the TCP port for this resource's replication links,
	// allocated cluster-wide by the controller at creation.
	// +kubebuilder:validation:Minimum=1024
	// +kubebuilder:validation:Maximum=65535
	Port int32 `json:"port"`
	// SharedSecret authenticates peers (cram-hmac-alg challenge-response):
	// without it, anything that can reach the replication port can join the
	// resource. Generated by the controller at creation; both agents render
	// the same value. DRBD caps secrets at 64 characters.
	// +kubebuilder:validation:MaxLength=64
	// +optional
	SharedSecret string `json:"sharedSecret,omitempty"`
	// BitmapGranularityBytes is the DRBD bitmap block size handed to
	// create-md (--bitmap-block-size): each dirty bit tracks this many
	// bytes, so coarser bits cut bitmap RAM proportionally at the cost of
	// resyncing more per dirty bit. Applied only when a replica's metadata
	// is first created — replicas created earlier keep their granularity
	// (DRBD exchanges bitmaps across differing block sizes). 0 means the
	// DRBD default (4096). Needs kmod ≥ 9.3.1 (the agent's startup floor).
	// +kubebuilder:validation:Enum=0;4096;8192;16384;32768;65536;131072;262144;524288;1048576
	// +optional
	BitmapGranularityBytes int64 `json:"bitmapGranularityBytes,omitempty"`
}

// VolumeSource provisions the volume's content from an existing snapshot.
type VolumeSource struct {
	// SnapshotName references a MiroirSnapshot by name.
	SnapshotName string `json:"snapshotName"`
	// PadForMetadata marks every diskful backing of this volume as padded
	// by the DRBD internal-metadata overhead. Set at creation when a
	// restore crosses the replication boundary (an unreplicated source
	// restored into a replicated volume, directly or transitively): the
	// source filesystem spans its full nominal size, so internal metadata
	// only fits if every leg's backing is grown past sizeBytes — the
	// clone before create-md, and full-sync joiners at creation, or the
	// device would size below the filesystem. Inherited by replicated
	// restores of padded volumes; immutable with the rest of the source.
	// +optional
	PadForMetadata bool `json:"padForMetadata,omitempty"`
}

// VolumeClient is an ephemeral diskless consumer leg: a DRBD peer with no
// backing device on a node that runs a pod but holds no replica. All its
// I/O crosses the replication network. Added by the CSI node service at
// stage time (spec.allowRemoteAccess volumes only), completed by the
// membership reconciler like a replica, removed at unstage. Unlike a
// diskless tie-breaker it is not placed for quorum, and it is rendered
// with "tiebreaker no" so DRBD never counts its vote — attach/detach
// leaves the majority threshold alone (docs: remote-consumers).
type VolumeClient struct {
	// Node is the Kubernetes node name consuming the volume remotely.
	Node string `json:"node"`
	// NodeID is the DRBD node id, unique across replicas and clients,
	// assigned by the membership reconciler.
	// +optional
	NodeID int32 `json:"nodeID,omitempty"`
	// Address is the replication endpoint, resolved like a replica's
	// (node-map override, else the Node's InternalIP).
	// +optional
	Address string `json:"address,omitempty"`
	// AddedAt is when the CSI node service attached this leg. The
	// auto-diskful reconciler keys its conversion threshold on it.
	// +optional
	AddedAt *metav1.Time `json:"addedAt,omitempty"`
}

// ExportSpec turns the volume into a shared filesystem (RWX): a gateway
// pod on one replica node stages the device and serves it over NFS;
// consumers on any node mount the export. The gateway is the volume's
// only writer, so DRBD single-primary fencing is unchanged (no
// allow-two-primaries). Set at creation from a MULTI_NODE access mode
// and immutable thereafter.
type ExportSpec struct {
	// FSType is the filesystem the gateway formats and mounts on the
	// device. Persisted here because mkfs happens in the gateway, which
	// never sees a CSI VolumeCapability; consumers only ever see NFS.
	// +kubebuilder:validation:Enum=ext4;xfs
	FSType string `json:"fsType"`
}

// DiskfulReplicas returns the non-diskless replicas — those that hold
// actual data. Use this instead of the raw slice where diskless
// tie-breakers must be excluded (capacity, phase, snapshot barrier).
func (s MiroirVolumeSpec) DiskfulReplicas() []Replica {
	out := make([]Replica, 0, len(s.Replicas))
	for _, r := range s.Replicas {
		if !r.Diskless {
			out = append(out, r)
		}
	}
	return out
}

// FirstDiskfulReplica returns the first non-diskless replica, or nil if
// there are none. Use where Replicas[0] was previously assumed diskful
// (resize coordinator, snapshot coordinator fallback).
func (s MiroirVolumeSpec) FirstDiskfulReplica() *Replica {
	for i := range s.Replicas {
		if !s.Replicas[i].Diskless {
			return &s.Replicas[i]
		}
	}
	return nil
}

// MiroirVolumeSpec is the desired state, written by the controller at
// CreateVolume time and reconciled by node agents. Replicas may be edited
// on a live replicated volume — add an entry (node + backend; the
// membership reconciler completes it) or remove one — within the bounds
// the validation rule pins: an unreplicated volume cannot grow a
// replication layer in place (internal DRBD metadata cannot be added
// under a live filesystem), and a replicated one keeps 2–3 replicas.
// +kubebuilder:validation:XValidation:rule="has(self.drbd) ? (size(self.replicas) >= 2 && size(self.replicas) <= 3) : size(self.replicas) == 1",message="replicated volumes (spec.drbd set) need 2-3 replicas; unreplicated exactly 1"
// +kubebuilder:validation:XValidation:rule="has(self.drbd) ? size(self.replicas.filter(r, !has(r.diskless) || !r.diskless)) >= 2 : true",message="replicated volumes need at least 2 diskful (non-diskless) replicas"
// +kubebuilder:validation:XValidation:rule="!has(self.drbd) ? !self.replicas.exists(r, has(r.diskless) && r.diskless) : true",message="diskless replicas are only valid on replicated volumes"
// +kubebuilder:validation:XValidation:rule="size(self.replicas) > 0 ? !has(self.replicas[0].diskless) || !self.replicas[0].diskless : true",message="the first replica must be diskful (not a diskless tie-breaker)"
// +kubebuilder:validation:XValidation:rule="self.replicas.all(r, oldSelf.replicas.all(o, o.node != r.node || (has(o.diskless) && o.diskless) || !(has(r.diskless) && r.diskless)))",message="a diskful replica cannot become diskless in place; remove the replica and re-add it instead (diskless→diskful is allowed: the agent attaches a disk to the live leg)"
// +kubebuilder:validation:XValidation:rule="self.replicas.all(r, oldSelf.replicas.all(o, o.node != r.node || (has(o.diskless) && o.diskless) || !has(o.address) || (has(o.pool) ? o.pool : 'default') == (has(r.pool) ? r.pool : 'default')))",message="a completed replica's pool is immutable: the agent would realize a fresh device in the new pool and abandon the old one; remove the replica and re-add it in the target pool instead"
// +kubebuilder:validation:XValidation:rule="self.replicas.all(r, (has(r.diskless) && r.diskless) || !has(r.address) || self.replicas.all(o, (has(o.diskless) && o.diskless) || !has(o.address) || (has(r.pool) ? r.pool : 'default') == (has(o.pool) ? o.pool : 'default')))",message="all diskful replicas must live in one pool: snapshots and restores are pool-local, so a mixed-pool volume's snapshots would be unrestorable"
// +kubebuilder:validation:XValidation:rule="has(self.drbd) == has(oldSelf.drbd)",message="a volume cannot gain or lose its replication layer in place"
// +kubebuilder:validation:XValidation:rule="!has(self.clients) || has(self.drbd)",message="client legs are only valid on replicated volumes"
// +kubebuilder:validation:XValidation:rule="!has(self.clients) || self.clients.all(c, !self.replicas.exists(r, r.node == c.node))",message="a client leg cannot share a node with a replica"
// +kubebuilder:validation:XValidation:rule="!has(self.clients) || !has(self.export)",message="an NFS-exported (RWX) volume is consumed over NFS and cannot have DRBD client legs"
// +kubebuilder:validation:XValidation:rule="has(self.export) == has(oldSelf.export)",message="a volume cannot gain or lose its NFS export (RWX) in place"
// +kubebuilder:validation:XValidation:rule="!(has(self.export) && has(self.drbd)) || self.quorumPolicy == 'freeze'",message="replicated RWX volumes must use freeze quorum (a rescheduled gateway under last-man-standing risks dual-primary split-brain)"
// +kubebuilder:validation:XValidation:rule="self.replicas.all(r, self.replicas.exists_one(o, o.node == r.node))",message="replica nodes must be unique: a node holds at most one leg of a volume"
// +kubebuilder:validation:XValidation:rule="!has(self.clients) || self.clients.all(c, self.clients.exists_one(o, o.node == c.node))",message="client-leg nodes must be unique"
// +kubebuilder:validation:XValidation:rule="!has(self.drbd) || !has(oldSelf.drbd) || self.drbd.port == oldSelf.drbd.port",message="drbd.port is immutable: it was allocated cluster-wide at creation and the allocator assumes existing volumes keep their ports"
// +kubebuilder:validation:XValidation:rule="has(self.source) == has(oldSelf.source) && (!has(self.source) || !has(oldSelf.source) || (self.source.snapshotName == oldSelf.source.snapshotName && (has(self.source.padForMetadata) && self.source.padForMetadata) == (has(oldSelf.source.padForMetadata) && oldSelf.source.padForMetadata)))",message="source is immutable: it records the snapshot and metadata padding this volume was cloned with"
// +kubebuilder:validation:XValidation:rule="!has(self.export) || !has(oldSelf.export) || self.export.fsType == oldSelf.export.fsType",message="export.fsType is immutable: the gateway formatted the volume with it at first start"
type MiroirVolumeSpec struct {
	// SizeBytes is the provisioned (virtual, thin) size of the volume.
	// The transition rule pins it monotonic: nothing downstream supports
	// shrinking — agents only grow the backing device and the filesystem,
	// and a shrunk spec would desync DRBD metadata from the device.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:XValidation:rule="self >= oldSelf",message="a volume cannot shrink in place: agents only grow the backing device and filesystem; restore a snapshot into a new, smaller volume instead"
	SizeBytes int64 `json:"sizeBytes"`
	// Replicas lists the placement of the volume: one entry for local
	// volumes, two or more for DRBD-replicated ones. MaxItems matches the
	// CEL size rule and bounds the apiserver's CEL cost estimate — the
	// diskless transition rule is nested over this list and exceeds the
	// rule budget on an unbounded array.
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=3
	Replicas []Replica `json:"replicas"`
	// QuorumPolicy applies only when len(Replicas) > 1.
	// +optional
	QuorumPolicy QuorumPolicy `json:"quorumPolicy,omitempty"`
	// DRBD is set by the controller when len(Replicas) > 1.
	// +optional
	DRBD *DRBDSpec `json:"drbd,omitempty"`
	// Source, if set, provisions content from a snapshot (CoW clone).
	// +optional
	Source *VolumeSource `json:"source,omitempty"`
	// AllowRemoteAccess permits pods on nodes without a replica: the PV
	// carries no node affinity, and staging on a non-replica node attaches
	// an ephemeral diskless client leg (spec.clients). From the
	// StorageClass parameter; replicated volumes only.
	// +optional
	AllowRemoteAccess bool `json:"allowRemoteAccess,omitempty"`
	// Clients are ephemeral diskless consumer legs, added at stage time on
	// non-replica nodes and removed at unstage. Bounded small: RWO means
	// one consumer, plus headroom for an attach/detach overlap during a
	// pod move.
	// +optional
	// +kubebuilder:validation:MaxItems=2
	Clients []VolumeClient `json:"clients,omitempty"`
	// Export, if set, serves the volume as a shared filesystem over NFS
	// (RWX). Set by the controller when the volume is created from a
	// MULTI_NODE access mode; immutable.
	// +optional
	Export *ExportSpec `json:"export,omitempty"`
}

// ClientForNode returns the client leg on the given node, or nil.
func (s MiroirVolumeSpec) ClientForNode(node string) *VolumeClient {
	for i := range s.Clients {
		if s.Clients[i].Node == node {
			return &s.Clients[i]
		}
	}
	return nil
}

// ReplicaStatus is the per-node observed state, written by that node's agent.
type ReplicaStatus struct {
	// DeviceCreated is true once the backing device exists on the node.
	DeviceCreated bool `json:"deviceCreated"`
	// DevicePath is the node-local path pods attach to (backing device for
	// replicas:1; /dev/drbd<minor> when replicated).
	DevicePath string `json:"devicePath,omitempty"`
	// SizeBytes is the currently realized size on this node, used to
	// acknowledge expansion.
	SizeBytes int64 `json:"sizeBytes,omitempty"`
	// DRBDMinor is the DRBD device minor assigned locally by the agent.
	// Zero means unassigned (fresh volume or unreplicated).
	// +optional
	DRBDMinor int32 `json:"drbdMinor,omitempty"`
	// DiskState is the DRBD disk state on this node (UpToDate,
	// Inconsistent, Outdated, Diskless, …). Empty for unreplicated volumes.
	// +optional
	DiskState string `json:"diskState,omitempty"`
	// Connected is true when this node's replication links to every
	// diskful peer are established. A diskless tie-breaker's link state
	// is deliberately excluded: it holds no data leg, so its downtime
	// must not read as degraded replication (it would block snapshots
	// and replica removal). Always true for unreplicated volumes.
	// +optional
	Connected bool `json:"connected"`
	// SplitBrain is true when this node's DRBD refused a reconnect after
	// detecting divergent data — operator intervention required.
	// +optional
	SplitBrain bool `json:"splitBrain"`
	// Diskless records that this node's replica is a quorum-only
	// tie-breaker. Self-reported by the agent so removal handling still
	// knows after the entry has left spec.replicas.
	// +optional
	Diskless bool `json:"diskless,omitempty"`
	// Pool records which storage pool holds this leg's backing device.
	// Self-reported by the agent like Diskless, so teardown after the
	// entry has left spec.replicas still targets the right pool. Empty
	// means the default pool.
	// +optional
	Pool string `json:"pool,omitempty"`
	// DiscardGranularityBytes is the discard granularity this diskful
	// leg probed from its backing device (0: unsupported or unprobed).
	// Client legs advertise the max over the diskful legs' values, so
	// trims from remote consumers align with the real backings instead
	// of the 512-byte default DRBD assumes for diskless devices.
	// +optional
	DiscardGranularityBytes int64 `json:"discardGranularityBytes,omitempty"`
	// DiskFailed latches a diskful leg DRBD detached after a backing I/O
	// error (on-io-error detach): the agent renders `adjust --skip-disk`
	// so the next reconcile does not re-attach the failing disk and
	// re-trigger the error. Sticky until the replica is removed and
	// re-added (a fresh backing clears it). Serving continues via the peer.
	// +optional
	DiskFailed bool `json:"diskFailed,omitempty"`
	// Message carries the last reconcile error, if any.
	Message string `json:"message,omitempty"`
	// PrimarySince is when this node's leg last became DRBD Primary (a
	// consumer holds the device open); cleared on demotion. Maintained by
	// the agent from the kernel role, so it survives unstage bookkeeping
	// being skipped (force-killed pods). The auto-diskful reconciler keys
	// tie-breaker conversion on its age.
	// +optional
	PrimarySince *metav1.Time `json:"primarySince,omitempty"`
	// LastVerifyTime is when the last scheduled online verify completed for
	// this volume. Only the coordinator (first diskful replica) initiates a
	// verify, so only its slot carries this.
	// +optional
	LastVerifyTime *metav1.Time `json:"lastVerifyTime,omitempty"`
	// LastVerifyOutOfSyncBytes is the out-of-sync total the last verify
	// found (0 = clean). Findings need a disconnect/connect cycle to resync;
	// they persist in the out-of-sync metric until then. A pointer so a
	// clean verify (0) reads differently from "never verified" (nil).
	// +optional
	LastVerifyOutOfSyncBytes *int64 `json:"lastVerifyOutOfSyncBytes,omitempty"`
	// LastProbedAt is when this agent last successfully probed the
	// replica's live state (backing device, DRBD status). A stale probe
	// means the agent can no longer reach the node-local resources —
	// computePhase treats it as Degraded even when persisted fields still
	// read as healthy, mirroring the Linstor pattern of distinguishing
	// "exists in CRD" from "live and reachable."
	// +optional
	LastProbedAt *metav1.Time `json:"lastProbedAt,omitempty"`
}

// ExportStatus is the observed state of an RWX volume's NFS gateway,
// written by the export reconciler.
type ExportStatus struct {
	// Address is the share Service's ClusterIP. Consumers mount
	// <address>:/<volume> over NFS. Empty until the reconciler has
	// created the Service and read back its allocated ClusterIP.
	// +optional
	Address string `json:"address,omitempty"`
}

// MiroirVolumeStatus is the observed state aggregated from node agents.
type MiroirVolumeStatus struct {
	// Phase summarizes the volume state for the controller and humans.
	// +optional
	Phase VolumePhase `json:"phase,omitempty"`
	// ReadyReplicas summarizes diskful replica readiness as "ready/total"
	// (diskless tie-breakers and client legs excluded, like Phase). A
	// preformatted string because CRD printcolumns cannot combine two
	// integer fields into one cell.
	// +optional
	ReadyReplicas string `json:"readyReplicas,omitempty"`
	// PerNode maps node name to that agent's observed state.
	// +optional
	PerNode map[string]ReplicaStatus `json:"perNode,omitempty"`
	// Export is the observed state of the NFS gateway, set only on RWX
	// volumes (spec.export). Written by the export reconciler.
	// +optional
	Export *ExportStatus `json:"export,omitempty"`
	// Formatted is set once the volume has ever carried a filesystem —
	// first mkfs at stage time, or inherited from the snapshot source on
	// restore. A blank device on a formatted volume is data loss: the
	// node refuses to mkfs again rather than silently wipe it.
	// +optional
	Formatted bool `json:"formatted,omitempty"`
	// Activated is set the first time any node successfully stages the
	// volume for a consumer (filesystem or raw block). It latches "this
	// volume may hold data": split-brain auto-recovery, which discards one
	// leg's generation, runs only while this is false — on an activated
	// volume divergence is never auto-resolved. Broader than Formatted,
	// which a raw-block volume never sets.
	// +optional
	Activated bool `json:"activated,omitempty"`
	// Conditions follow the standard Kubernetes condition conventions.
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Cluster,shortName=miv
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Size",type=integer,JSONPath=`.spec.sizeBytes`
// +kubebuilder:printcolumn:name="Replicas",type=string,JSONPath=`.status.readyReplicas`
// +kubebuilder:printcolumn:name="Pools",type=string,JSONPath=`.spec.replicas[*].pool`,priority=1
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// MiroirVolume is one provisioned volume (1:1 with a PV).
type MiroirVolume struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MiroirVolumeSpec   `json:"spec"`
	Status MiroirVolumeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MiroirVolumeList contains a list of MiroirVolume.
type MiroirVolumeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MiroirVolume `json:"items"`
}
